---
kit:
  name: dev
  version: latest
  features:
    - self-signed-cert

genesis:
  env: base    

params:
  external_domain:      test.domain
  static_ip:            10.1.1.1
  persistent_disk_type: default
  network: prometheus
  bosh_exodus_path: base/prometheus
