secret/base/prometheus/admin:
  password: <!{meta.vault}/admin:password!>
  secret_key: <!{meta.vault}/admin:secret_key!>
secret/base/prometheus/grafanadb:
  password: <!{meta.vault}/grafanadb:password!>
secret/base/prometheus/nginx/ca:
  certificate: <!{meta.vault}/nginx/ca:certificate!>
  combined: <!{meta.vault}/nginx/ca:combined!>
  crl: <!{meta.vault}/nginx/ca:crl!>
  key: <!{meta.vault}/nginx/ca:key!>
  serial: <!{meta.vault}/nginx/ca:serial!>
secret/base/prometheus/nginx/ssl_certificate:
  certificate: <!{meta.vault}/nginx/ssl_certificate:certificate!>
  combined: <!{meta.vault}/nginx/ssl_certificate:combined!>
  key: <!{meta.vault}/nginx/ssl_certificate:key!>
