---
# Contains the defaults for the parameters needed for the base prometheus kit.
params:
  availability_zones: [ z1 ]
  disk_pool: prometheus
  vm_type: small
  network: default
  stemcell_os: ubuntu-trusty
  stemcell_version: latest
