---
meta:
  vault: (( concat "secret/" params.vault "/" ))
  grafanadb_password: (( vault meta.vault "grafanadb:password" ))

name: (( concat params.env "-prometheus" ))
instance_groups:
- instances: 1
  azs: (( grab params.availability_zones ))
  stemcell: default
  name: prometheus
  networks:
  - name: (( grab params.network ))
  persistent_disk_pool: (( grab params.disk_pool ))
  vm_type: (( grab params.vm_type ))
  jobs:
  - name: alertmanager
    release: prometheus
  - name: prometheus
    release: prometheus
  - name: pushgateway
    release: prometheus
  - name: grafana
    release: prometheus
  - name: postgres
    release: postgres
  - name: probe_alerts
    release: prometheus
  - name: probe_dashboards
    release: prometheus
  - name: prometheus_alerts
    release: prometheus
  - name: prometheus_dashboards
    release: prometheus
  - name: system_dashboards
    release: prometheus

  # need subkits:
  #- name: consul_alerts
  #  release: prometheus
  #- name: consul_dashboards
  #  release: prometheus
  #- name: consul_exporter
  #  release: prometheus
  #- name: haproxy_alerts
  #  release: prometheus
  #- name: haproxy_dashboards
  #  release: prometheus
  #- name: haproxy_exporter
  #  release: prometheus
  #- name: kubernetes_alerts
  #  release: prometheus
  #- name: kubernetes_dashboards
  #  release: prometheus
  #- name: kubernetes_exporter
  #  release: prometheus
  #- name: mysql_alerts
  #  release: prometheus
  #- name: mysql_dashboards
  #  release: prometheus
  #- name: mysql_exporter
  #  release: prometheus
  #- name: p_rabbitmq_alerts
  #  release: prometheus
  #- name: p_rabbitmq_dashboards
  #  release: prometheus
  #- name: p_rabbitmq_exporter
  #  release: prometheus
  #- name: p_redis_alerts
  #  release: prometheus
  #- name: p_redis_dashboards
  #  release: prometheus
  #- name: p_redis_exporter
  #  release: prometheus
  #- name: redis_alerts
  #  release: prometheus
  #- name: redis_dashboards
  #  release: prometheus
  #- name: redis_exporter
  #  release: prometheus
properties:
  alertmanager:
    receivers:
    - name: default-receiver
    route:
      receiver: default-receiver
  grafana:
    dashboards:
      json:
        enabled: true
    database:
      host: 127.0.0.1
      name: grafanadb
      password: (( grab meta.grafanadb_password ))
      type: postgres
      user: grafanadbadmin
    prometheus:
      dashboard_files: 
      - /var/vcap/jobs/prometheus_dashboards/*.json
      - /var/vcap/jobs/system_dashboards/*.json
      # need subkits:
      #- /var/vcap/jobs/consul_dashboards/*.json
      #- /var/vcap/jobs/haproxy_dashboards/*.json
      #- /var/vcap/jobs/kubernetes_dashboards/*.json
      #- /var/vcap/jobs/mysql_dashboards/*.json
      #- /var/vcap/jobs/p_rabbitmq_dashboards/*.json
      #- /var/vcap/jobs/p_redis_dashboards/*.json
      #- /var/vcap/jobs/redis_dashboards/*.json
    security:
      admin_password: (( vault meta.vault "grafana:password" ))
      admin_user: admin
      secret_key: (( vault meta.vault "grafana:secret_key" ))
    session:
      provider: postgres
      provider_config: (( concat "user=grafanadbadmin password=" meta.grafanadb_password " host=127.0.0.1 dbname=grafanadb port=5432 sslmode=disable" ))
  nginx:
    alertmanager:
      auth_password: (( vault meta.vault "grafana:password" ))
      auth_username: admin
    prometheus:
      auth_password: (( vault meta.vault "grafana:password" ))
      auth_username: admin
  pgpool:
    databases:
    - extensions:
      - citext
      - pgcrypto
      name: grafanadb
      users:
      - grafanadbadmin
    users:
    - password: (( grab meta.grafanadb_password ))
      username: grafanadbadmin
  postgres:
    config:
      listen_addresses: '*'
      port: 5432
    hba:
    - host all all 0.0.0.0/0 md5
    - host all all ::/0 md5
    replication:
      enabled: false
  prometheus:
    rule_files:
    - /var/vcap/jobs/prometheus_alerts/*.alerts
    # need subkits:
    #- /var/vcap/jobs/consul_alerts/*.alerts
    #- /var/vcap/jobs/haproxy_alerts/*.alerts
    #- /var/vcap/jobs/kubernetes_alerts/*.alerts
    #- /var/vcap/jobs/mysql_alerts/*.alerts
    #- /var/vcap/jobs/p_rabbitmq_alerts/*.alerts
    #- /var/vcap/jobs/p_redis_alerts/*.alerts
    #- /var/vcap/jobs/redis_alerts/*.alerts
    scrape_interval: 30s
    scrape_timeout: 30s
    scrape_configs:
    - job_name: bosh
      scrape_interval: 1m
      scrape_timeout: 1m
      static_configs:
        - targets:
          - localhost:9190
    - job_name: bosh_tsdb
      file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
      relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: bosh_tsdb_exporter
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9194"
    - job_name: cf
      scrape_interval: 4m
      scrape_timeout: 2m
      file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
      relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: cf_exporter
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9193"
    - job_name: collectd
      file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
      relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: collectd_exporter
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9103"
    - job_name: consul
      file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
      relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: consul_exporter
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9107"
    - job_name: elasticsearch
      file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
      relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: elasticsearch_exporter
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9114"
    - job_name: firehose
      file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
      relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: firehose_exporter
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9186"
    - job_name: github
      file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
      relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: github_exporter
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9171"
    - job_name: graphite
      file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
      relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: graphite_exporter
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9108"
    - job_name: haproxy
      file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
      relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: haproxy_exporter
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9101"
    - job_name: influxdb
      static_configs:
        - targets:
          - localhost:9122
    - job_name: kubernetes
      file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
      relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: kube_state_metrics_exporter
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9188"
    - job_name: memcached
      file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
      relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: memcached_exporter
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9150"
    - job_name: mysql
      static_configs:
        - targets:
          - localhost:9104
    - job_name: nats
      file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
      relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: nats_exporter
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9118"
    - job_name: node
      file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
      relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: node_exporter
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9100"
    - job_name: postgres
      file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
      relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: postgres_exporter
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9187"
    - job_name: prometheus
      file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
      relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: prometheus
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9090"
    - job_name: pushgateway
      file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
      relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: pushgateway
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9091"
    - job_name: rabbitmq
      file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
      relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: rabbitmq_exporter
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9125"
    - job_name: redis
      file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
      relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: redis_exporter
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9121"
    - job_name: shield
      scrape_interval: 4m
      scrape_timeout: 2m
      file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
      relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: shield_exporter
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9179"
    - job_name: stackdriver
      file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
      relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: stackdriver_exporter
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9255"
    - job_name: statsd
      file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
      relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: statsd_exporter
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9102"
releases:
- name: postgres
  version: 1.0.4
  url: https://github.com/cloudfoundry-community/postgres-boshrelease/releases/download/v1.0.4/postgres-1.0.4.tgz
  sha1: 8b82c86b7763abdb8f117523b852d1e1c9a20eeb
- name: prometheus
  version: 17.4.2
  url: https://bosh.io/d/github.com/cloudfoundry-community/prometheus-boshrelease?v=17.4.2
  sha1: 72686b66f5f018326c761e05d61d9235a6500ac5
- name: shield
  version: latest
stemcells:
- alias: default
  os: (( grab params.stemcell_os ))
  version: (( grab params.stemcell_version ))
update:
  canaries: 1
  canary_watch_time: 1000-120000
  max_in_flight: 1
  serial: true
  update_watch_time: 1000-120000

